# Generated by Django 5.2 on 2025-04-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=20)),
                ('idProducto', models.CharField(max_length=10)),
                ('stock', models.CharField(max_length=8)),
                ('fechaIngreso', models.DateField(null=True)),
            ],
        ),
    ]
