# Generated by Django 5.2 on 2025-04-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductosApp', '0002_producto_productoimagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='productoImagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
    ]
