# Generated by Django 5.2 on 2025-04-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsuariosApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoextra',
            name='fechaNacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
